### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by PinkDiamond1** [OLSF/libra#1017]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
- 

## Additional context

@

**Comment by PinkDiamond1** [comment]
975e038e912af29fc171823876c5a3bd0396aa2cfdd6a013012823b7d432ccf1

**Comment by 0xzoz** [comment]
Not enough information was provided.
