### ISSUE TITLE
BUG: Validator failover not implemented to spec

### ISSUE THREAD

**Issue by sm86** [OLSF/libra#1063]
Investigate the validator set when everyone is inactive. Currently it goes to 100 nodes. 

Ideally should have the current validator set if no one qualifies

**Comment by jamesmeijers** [comment]
PR for this #1069

**Comment by sm86** [comment]
this might not address the issue we have. 
If network is halted and none of the validators submit proofs, we continue to have all top_accounts

**Comment by sm86** [comment]
### Proposed algo: 
proposed set  = the list of not jailed eligible validators (submitted threshold proofs)
if size(proposed set) < 3:
    top 50% of previous epoch's validator set sorted by tower height

// the above is recursive, gradually reducing the size of network while halted. 
base case: ensure at least 10 validators in the set

### Assumptions
Assumes at least 7 out of top 10 validators (sorted by tower height) are active

**Comment by 0o-de-lally** [comment]
Thanks @sm86  this is useful. Can you propose some sample Move code?

**Comment by 0o-de-lally** [comment]
@jamesmeijers Thanks for the fast turn around on this! What do you think of the feasibility of Sha's proposal?

**Comment by jamesmeijers** [comment]
> If network is halted and none of the validators submit proofs, we continue to have all top_accounts
I don't think so, in this case it will revert to the old validator set. @0o-de-lally unless I'm wrong that `ValidatorUniverse::get_eligible_validators(vm);` returns the full list of potential validators regardless of their mining in the last epoch. The reason I added the loop to check if validators are in that set is in case a validator removed themselves from the set. 

That said, I think the gradual reduction proposal seems reasonable.

**Comment by sm86** [comment]
might be a special case but right now we have 100 validators and none of them submit proofs since network halted - so we might end up with same validator set every epoch and never reach consensus

**Comment by sm86** [comment]
@0o-de-lally and @jamesmeijers let me share some Move code soon

**Comment by 0o-de-lally** [comment]
Fixed with https://github.com/OLSF/libra/pull/1118
