### ISSUE TITLE
[Chore] Refactor `.unwrap()` with Match in Codebase

### ISSUE THREAD

**Issue by 0xzoz** [OLSF/libra#1144]
# 👷🏾 Chore

> This should be done using the `v6` branch as the main has been frozen while we wait to upgrade the network.
> GRADUATION DEADLINE: To graduate from the Tool Scrubbers Guild's first course. You must submit [10 `.unwrap()` refactors](https://github.com/OLSF/libra/issues/1144) and [10 `.clone()` refactors](https://github.com/OLSF/libra/issues/1143). This should be submitted by 05/10/22.

## What is the issue

During the development of the initial implementation of 0L. Work was done quickly to meet deadlines and because of this `.unwrap()` was used in some instances to speed up development. These need to be cleaned up. 

## What needs to be done?

- Go through the `/ol` folder in the root and remove instances of `.unwrap()` by refactoring the code and adding a match statement. This may include refactoring of related files that the code is coupled to. 

## How to go about this?

If you take a section of this please open up a task in the tool-scrubbers-repo project board with the file or folder you are working on and comment below. This issue will add a checkbox here to keep track of what has been done.

- [X] `/ol/cli` - @0xzoz 
- [ ] `/ol/devnet`
- [ ] `/ol/documentation`
- [ ] `/ol/fixtures`
- [ ] `/ol/genesis-tools`
- [ ] `/ol/integration-tests`
- [ ] `/ol/keys`
- [X] `/ol/onboard` - @The1OneID 
- [ ] `/ol/tower`
- [X] `/ol/txs` - @nimadebi 
- [X] `/ol/types` - @MichaelZelbel
- [X] `/ol/util` - @mortonbits 
- [ ] `/ol/verifiable_delay`

**Comment by The1OneID** [comment]
https://github.com/OLSF/libra/pull/1145

**Comment by 0xzoz** [comment]
I'll take care of the cli folder

**Comment by The1OneID** [comment]
I'm working in the onboard folder

**Comment by The1OneID** [comment]
#1151

**Comment by MichaelZelbel** [comment]
I can try working on the types folder

**Comment by nimadebi** [comment]
I'll work on txs folder

**Comment by 0xzoz** [comment]
@nimadebi @mortonbits @MichaelZelbel  @nControl88 @simyounghyun @The1OneID These tasks have been broken out into sub folders as separate issues to be more specific. Each folder now has a bounty attached to it for 2000 GAS. I will @ the owners in each of the issues and then close this
