### ISSUE TITLE
[Documentation] readme typos

### ISSUE THREAD

**Issue by shawnharmsen** [OLSF/libra#1255]
### What is the issue
Readme has typos and grammar issues that is an easy fix for legibility

### What needs to be done?
- PR linked: https://github.com/0LNetworkCommunity/libra/pull/1256

### Intention
- I did not see a documentation template in the issue templates and just a documentation tag so I used the [Chore] template

**Comment by MamathaKarapanahalli** [comment]
Hi, can I take this issue up and work on it? 

Thanks,
Mamatha
