### ISSUE TITLE
[Move] Use Error module for error reporting

### ISSUE THREAD

**Issue by lpgeiger** [OLSF/libra#329]
Need to decide on best practices for using "Error" module.

Error:: surfaces descriptive errors on CLI, TXs, and tests.

Many 0L mods predate the new error framework.

Implement new Error module throughout .move source for descriptive traces.

However, it is good to have specific error numbers per assert, which makes it easy to chase down the error. So some kind of compromise would be good.

**Comment by lpgeiger** [comment]
@sm86 Are you able to work on this? Should be fairly straightforward to use with your error code semantics.

**Comment by sm86** [comment]
Is this just going through Move modules and verifying if error semantics are followed?

**Comment by lpgeiger** [comment]
Since last merge with upstream Libra includes an Error type, which we should use through out. We need to combine our approach of integer codes with the Error type. Reporting with error type will allow transaction senders to see what the error was, without referring to the code.

**Comment by lpgeiger** [comment]
closed with v4.3.0
