### ISSUE TITLE
[TXS] Non-interactive headless client

### ISSUE THREAD

**Issue by lpgeiger** [OLSF/libra#359]
## Goal:

Have a small command line utility that can submit many/all of the stdlib client transactions, without needing user interaction.

## Summary:
pull out the client transaction sending feature of miner into a standalone and more generalizable client.

## Example use case:
The CI servers need to submit "oracle upgrade" transactions, but don't have a tool for doing so.

## Background:
Certain operations like mining require sending transactions to network from a client. In the case of miner, there is a built client. This is an instance of LibraClient from testsuite/cli:

https://github.com/OLSF/libra/blob/5f9c3023161d1c5318d4e5d4ecb515d9e6bbb14c/miner/src/submit_tx.rs#L147-L148

Ideally there would be a separate "headless" client which could invoke any of the `transaction_builder` stdlib scripts: 

https://github.com/OLSF/libra/blob/987d082c136f7e9e28e5e5c953fb7d6ffe79b32b/client/transaction-builder/src/stdlib.rs#L0-L1

This headless utility would serve many purposes, such as sending transactions but also doing quick queries, which otherwise require logging into an interactive client.

## Implementation:
Much of the foundations for the headless client already exist in the `miner` package. see miner/src/submit_tx.rs.

Historically, the miner's submit_tx is based off of testsuite/cli::ClientProxy, but is more generalized.

If there is a headless cli tool, the `miner` app could then be refactored to import from that package.

## Txs Usage and Design:
https://github.com/OLSF/libra/blob/tx-sender/txs/README.md

## Currently Implemented Commands:
```
txs ... create-account -a /opt/account.json
txs ... oracle-upgrade -u /libra/fixtures/upgrade_payload/foo_stdlib.mv
```
Example usage using `create-account` cmd:  
```
// Get tx params from txs.toml (default) - e.g. ~/.0L/txs.toml
cargo r -p txs -- create-account -a ~/account.json                                    

// Get tx params from local swarm - some params hard coded in source code
cargo r -p txs -- -s ~/libra/swarm_temp create-account -a ~/account.json  

// Get/override some tx params from command line
cargo r -p txs -- -u "http://localhost:39513/" -w "0:5e65aa4ccfba16ed167f87f7dff8846b7eda315af90f88ac15d889758a744dda" create-account -a ~/account.json 

/// Also useful:
// Show txs flags
cargo r -p txs foo  // todo: this is a workaround, what is the correct way?

// Help <subcommand>
cargo r -p txs -- help create-account
```
## Next Actions:
- [x] Clean/push custom entrypoint code
- [x] Refactor/redesign get_tx_params()
- [x] Double check/clean: config.rs init_app_configs path() and_store.json not found log
- [ ] cargo r -p txs foo -> help text for `-s` not visible if more than 9 chars -> , details: https://github.com/OLSF/libra/issues/359#issuecomment-799190733
- [ ] Test oracle-upgrade commands for other cases - currently tested with swarm case (`-s` ...)

**Comment by simsekgokhan** [comment]
#### Currently Implemented Commands:
```
cargo r -p txs -- create-account -a /opt/account.json
cargo r -p txs -- oracle-upgrade -u /libra/fixtures/upgrade_payload/foo_stdlib.mv
```

**Comment by lpgeiger** [comment]
@simsekgokhan  I pushed some changes that load the tx params from CLI and Toml file. But only did this for create_account as a test. Maybe you can generalize?

**Comment by simsekgokhan** [comment]
@lpgeiger Sure, I will check.

**Comment by lpgeiger** [comment]
@simsekgokhan My suggestion is that are such as url, waypoint, and swarm-path, be in the main() of the app and not on the subcommands.
https://github.com/OLSF/libra/blob/a219877fffc7c6d11b4b5e2bdb75865ffa941367/txs/src/commands/create_account_cmd.rs#L20-L24

So currently 

`txs create-account --url 1.1.1.1`

Would be
`txs --url 1.1.1.1 create-account`

**Comment by lpgeiger** [comment]
@tarcieri is there a pattern to do this in abscissa?

**Comment by tarcieri** [comment]
Yep, check out how the `Entrypoint` command is defined:

https://github.com/iqlusioninc/abscissa/blob/main/core/src/command/entrypoint.rs#L31

**Comment by simsekgokhan** [comment]
@lpgeiger I was also planning to discuss this exactly, I will check. Thanks!

**Comment by simsekgokhan** [comment]
Hi @tarcieri , any idea about this problem? Help text is not visible if the `EntryPoint` struct's property is more than 9 chars:
(looks like a limitation, maybe a way to adjust this limit)

```
// Problem: using `swarm-path` 

cargo r -p txs -- ..

FLAGS:
    -c, --config CONFIG       path to configuration file
    -h, --help                print help message
    -v, --verbose             be verbose
    -s, --swarm-path SWARM-PATH 
    -u, --url URL             URL to send tx
    -w, --waypoint WAYPOINT   waypoint to connect to

// Fixed: using `swarm-pat` instead of `swarm-path` fixes

cargo r -p txs -- ..

FLAGS:
    -c, --config CONFIG       path to configuration file
    -h, --help                print help message
    -v, --verbose             be verbose
    -s, --swarm-pat SWARM-PAT swarm path to get tx params from
    -u, --url URL             URL to send tx
    -w, --waypoint WAYPOINT   waypoint to connect to

```

Related code:   

https://github.com/OLSF/libra/blob/65297694c90febf33011154e5824ec67ba275e88/txs/src/entrypoint.rs#L38-L41
