### ISSUE TITLE
Consolidate terminal password entry

### ISSUE THREAD

**Issue by lpgeiger** [OLSF/libra#360]
There are a number of packages that need terminal mnemonic entry.  Because of circular dependencies, there are three implementations which are redundant:
- [x] miner/keygen
- [x] txs
- [x] config/mangement/genesis/init.rs 
- [x] testsuite/cli/main.rs
- [x] place `config/management/genesis/src/keyscheme.rs` into new keygen package 

The one in miner/keygen is the reference one. Perhaps pull that out into a module which doesn't cause dependency cycling. Or into the headless client.

**Comment by simsekgokhan** [comment]
Command to test genesis tool:
`cargo run -p libra-genesis-tool --release --  init --path=./ --namespace=alice`
// this command will create key_store.json in --path

**Comment by simsekgokhan** [comment]
Related changes in txs branch:  
-----
Make keygen independent package. Use it from txs. 4f3443e
Miner to use project's keygen package dd12782
testsuite/cli/main.rs to use project's keygen package 9c4817e
Genesis tool to use project's keygen package d5d95e8
