### ISSUE TITLE
Faster Sync for onboarding Validators

### ISSUE THREAD

**Issue by sm86** [OLSF/libra#363]
## Motivation
A validator is onboarded by mining VDF proofs and submitting the transaction. However, to sign the blocks and be rewarded, they have to sync with the network. The state sync takes long time (around 4 days for full node - 75 epochs). This would take even more as we progress on the chain. 

## Problem
Faster sync with the network to onboard the validators. Waypoints are generated per each epoch in Libra. In other words, sync from latest waypoint. Each waypoint has corresponding genesis.blob. We only have the network's first genesis blob. 

We have the latest waypoint, we need latest genesis.blob to sync the network. 

## Progress
Work in progress 
Related issues: #361 
Possible approach: https://github.com/OLSF/libra/blob/OLv4/consensus/consensus-types/src/block.rs#L137

**Comment by lpgeiger** [comment]
I don't think this strategy would work, since there doesn't seem to be a clear path from the Block type to a WriteSet. Or did I miss it?

 https://github.com/OLSF/libra/blob/OLv4/consensus/consensus-types/src/block.rs#L137

**Comment by earthwindfirewater** [comment]
OL restore allows catching up from archive.
