### ISSUE TITLE
[Doc] Genesis v4 Registration

### ISSUE THREAD

**Issue by simsekgokhan** [OLSF/libra#371]
@andrewpdickson @lpgeiger 

`"... Rust, version should be 1.4.6"`
https://github.com/OLSF/libra/wiki/Genesis-v4-Registration#troubleshooting

Should this be 1.46.0? 
Or maybe even better to add "... refer to this file: https://github.com/OLSF/libra/blob/OLv4/rust-toolchain" ?

**Comment by andrewpdickson** [comment]
Gokhan -- yes, I think updating it to reflect the latter makes a lot of
sense!

**Comment by simsekgokhan** [comment]
Good, updated the doc.
