### ISSUE TITLE
[Feature Request] Autopay 2.0: Escrow when transaction is over account limit

### ISSUE THREAD

**Issue by lpgeiger** [OLSF/libra#381]
feature-branch: autopay-escrow

- [x] Merge branch `withdraw-limit`
- [x] Make autopay create escrow resource structs per recipient account
- [x] Autopay checks if transfers can pass threshold. If not difference goes into escrow.
- [x] Pay out from escrow on autopay tick
- [x] If more than one account waiting for escrow, divide withdraw limit equally among accounts.

**Comment by sm86** [comment]
I'd also request a feature for one-shot payment. This feature could internally use the existing functions.

**Comment by sm86** [comment]
Do we still need #346?

**Comment by lpgeiger** [comment]
> Do we still need #346?

closed

**Comment by lpgeiger** [comment]
@jamesmeijers  There's a stale branch that would increment autopay instructions, perhaps just pickout the relevant code from here: https://github.com/OLSF/libra/compare/autopay-increment

**Comment by jamesmeijers** [comment]
Discussed this with @lpgeiger today, here's what we will try: 
- Have each autopay payment over the account limit enter a FIFO escrow queue. This ensures that payees can reliably predict when they will get paid out (based on what is ahead of it in the queue)
- Pay out as much of the escrow queue at the beginning of each epoch (note, need to check into AccountLimits to ensure that the window is indeed reset at the beginning of the epoch, or else come up with another workaround) 

Using the FIFO method does raise some concerns. Most importantly is space, as a new item is appended to the queue for every autopay sent, so the space requirement is O(\#autopay commitments x \# epochs). Possible workarounds: 
- Limiting the number of autopay commitments each account can have
- Limiting the set of allowable autopay destinations (this would be tricky and ideally avoided imo)
- Potentially using the Event module to increase efficiency (not sure if this is possible, will investigate)

**Comment by jamesmeijers** [comment]
Code complete, but not enabled in #483
