### ISSUE TITLE
[Onboarding] Fullnode switches to Validator mode, without config changes

### ISSUE THREAD

**Issue by 0o-de-lally** [OLSF/libra#383]
Ideally when the fullnode is finally included in the validator set, the node should automatically switch.

Currently the node.yaml setting needs to be switched out at the time of entry into the validator set. I.e. the operator will have a fullnode.node.yaml, and a validator.node.yaml. 

This means the node operator needs to be aware of the first epoch change.

Related upstream:
https://github.com/diem/diem/pull/726

**Comment by lpgeiger** [comment]
@mortonbits @liangping 

I found an interesting test in the `smoke-tests`  test suite. It's  a test for the state-synchronizer using swarm. I was starting to write one myself, but it already exists: 

https://github.com/LOL-LLC/diem/blob/ce9d481447e8904091c1f18ff2fd405c7dc517c2/testsuite/smoke-test/src/state_sync.rs#L18

With `SmokeTestEnvironment` you can get a swarm of n fullnodes, n validator nodes.  and also control them:  `validator_swarm.kill_node(node_to_restart);` 

For your reference: Here's my makefile which does an integration test, but the smoke-tests will be better: https://github.com/LOL-LLC/libra/blob/5315e5374b7facadee32f0905e7922961c082669/ol/integration-tests/test-fullnode.mk
