### ISSUE TITLE
[Upgrade] Upgrade Oracle: move to leader based oracle, and use hashes in votes.

### ISSUE THREAD

**Issue by 0o-de-lally** [OLSF/libra#392]
### save space on chain

We would like to use hashes of the stdlib rather than the full stdlib in upgrade votes to save space on chain.

### reduce UI complexity for concurring votes

A voter who is concurring with a proposal need not install source and compile the stdlib to be able to submit a vote.

#### OracleUpgrade.move:

The move module has changes to structs. It must store the binary, and hash for the proposals. But only hash for the votes.

#### Tx Script:
- [x] If a binary is provided: the voting script should decide if this is a a new proposal or if it is concurring.
- [ ] Otherwise a hash must be provided, and will attempt to concur. If no hash is matched it is an error in the script.

## Rust code:
Voters will vote using the TXS app, which can vote with two methods:
- [x] as is currently done, with a binary. And in the case it is a new proposal, the binary must be provided.
- [x] by simply submitting a hash, if they are following the binary.

## Etc
A related Issue: https://github.com/OLSF/libra/issues/537

**Comment by lpgeiger** [comment]
@jamesmeijers Is this straightforward to include in v5? It's somewhat time sensitive.

**Comment by jamesmeijers** [comment]
> @jamesmeijers Is this straightforward to include in v5? It's somewhat time sensitive.

@lpgeiger yeah, pretty straightforward, see PR #672, I'll try to confirm everything early next week.

**Comment by jamesmeijers** [comment]
#672
