### ISSUE TITLE
Simple Block Explorer

### ISSUE THREAD

**Issue by sm86** [OLSF/libra#396]
# 🚀 Tool Request

## Motivation
The network is growing, would be good to see the current transactions, the addresses in the validator set and epoch which we are in. 
_Wanted to replace calendar dates with epoch numbers_ 

## MVP
Version 1 could just have the latest state info available on client - epoch number, current validator set.  https://github.com/OLSF/libra/blob/OLv4/testsuite/cli/src/info_commands.rs

Good to have Autopay pledges, which is unique to 0L project. 
Over time, we need to allow search by address, search by transaction, miner state. 

Should we explore some existing tools to clone?

**Comment by nelaturuk** [comment]
I think we should add block explorer. It's been outstanding for a long time.

**Comment by liangping** [comment]
I think it's very important to have a web-based explorer.

**Comment by lpgeiger** [comment]
Agree, potentially it could be a part of this, the Info Server: https://github.com/OLSF/libra/issues/399

This would mean every fullnode could serve a simple block explorer alongside its metrics. Fullnode decides if the port is open on 80 or 443.

**Comment by lpgeiger** [comment]
closed with #409
