### ISSUE TITLE
[Feature Request] Autopay transaction types

### ISSUE THREAD

**Issue by lpgeiger** [OLSF/libra#401]
Currently the Autopay experimental module uses a % of total balance. A fully featured autopay could include several instruction types.

- [x] % of current balance until x epoch
- [x] % of inflow of account in epoch (previous epoch?) until x epoch
- [x] flat rate every epoch until x epoch
- [x] flat rate one time

**Comment by jamesmeijers** [comment]
This is added here: https://github.com/jamesmeijers/libra/tree/autopay-escrow 

However I did it overwriting the current autopay module, which makes it a breaking upgrade. We can easily change that and create new data structures or put it in a new module if we'd like to avoid this

**Comment by lpgeiger** [comment]
Thanks @jamesmeijers! My suggestion is to give it a different module name, filename altogether while in development. That way you can keep the original (so that all the tests don't break, and will be annoying).

**Comment by jamesmeijers** [comment]
#483
