### ISSUE TITLE
[Feature Request] 0L changes as a module

### ISSUE THREAD

**Issue by lpgeiger** [OLSF/libra#418]
Goal: How to package 0L changes so that merging with upstream is less painful.

Ideally we would have a separate 0L module, which inherits from the Upstream. However we have changes to core files. This doesn't seem possible.

Idea: Could we have a less invasive modification if the Upstream was simply modified to import from a few 0L files (which are forked)

-----------
### Next Actions:  
- [x] Wrap all 0L changes with "0L comment" + and enforce this in code reviews?
- [x] Move 0L packages (miner, txs etc..) into `0L/` root folder
- [ ] Keep the original upstream file and the changed version with `_0L` suffix (e.g. `x.rs` and `x_0L.rs`)
- [ ] Perform merge upstream and write a guide for merge upstream

**Comment by simsekgokhan** [comment]
### Notes: 

**Auto-generated files:**  
\libra\client\transaction-builder\src\stdlib.rs

**Comment by lpgeiger** [comment]
@simsekgokhan  are you seeing opportunities for this while you are working on merge?

**Comment by simsekgokhan** [comment]
@lpgeiger Sure, I am keeping this in mind. But, have not seen yet.
