### ISSUE TITLE
[Bug] Autopay may trigger asserts that cause network halt

### ISSUE THREAD

**Issue by jamesmeijers** [OLSF/libra#423]
# 🐛 Bug

The block prologue, through AutoPay, may call functions (e.g. LibraAccount::deposit) that have assert statements. If these assert statements are triggered, the block prologue would fail and the network would be halted. 

## Additional context

The way I see it there are a few options: 
- Remove AutoPay from the block prologue (potentially not possible why still enabling AutoPay functionality) 
- Ensure, through code review, that AutoPay is implemented such that these assertions are never triggered 
- Remove these assertions (not ideal, as functions such as deposit are used by scripts as well) 
- Create a separate set of functions without assertions that are only used by LibraRoot
- Alter the assertions in question such that they have different behaviour if LibraRoot is the signer

**Comment by lpgeiger** [comment]
Good catch.
I think the short term is making sure that we check for sending a 0 GAS transaction in autopay.

The root cause needs to be solve. Which means a simple refactor of LibraAccount::vm_make_payment (which is an 0L mod), to not use asserts anywhere and just if/else control flow.

**Comment by lpgeiger** [comment]
@jamesmeijers  I think this is patched with vm_make_payment in  #409. Can you check?
