### ISSUE TITLE
[Bug] libra-node opens large number of file descriptors on sst files

### ISSUE THREAD

**Issue by dboreham** [OLSF/libra#424]
```
lsof -p $(pidof libra-node) | wc -l

2917
```

Most of the files are RocksDB SST files.

Observed on branch moonshot-cli but seems to be more widespread.

**Comment by dboreham** [comment]
Possibly an issue like this: https://stackoverflow.com/questions/56395061/rocksdb-compaction-not-triggered-or-not-happening

**Comment by dboreham** [comment]
On my node, I see the number of files in the db directory constantly increase:

```
root@meld:~/.0L/db/libradb# lsof -p 3067 | wc -l
3810
root@meld:~/.0L/db/libradb# lsof -p 3067 | wc -l
3831
root@meld:~/.0L/db/libradb# lsof -p 3067 | wc -l
3854
```

and the number of fds for the node process constantly increase:

```
root@meld:~/.0L/db/libradb# ls -l | wc -l
3759
root@meld:~/.0L/db/libradb# ls -l | wc -l
3815
root@meld:~/.0L/db/libradb# ls -l | wc -l
3821
```

Looks like a) sst files are not being purged on compaction, and b) a open file descriptor is being maintained on each of those files.

**Comment by lpgeiger** [comment]
Mine hover around 65k, which I think is an upperbound somewhere

**Comment by dboreham** [comment]
An area of interest: https://github.com/OLSF/libra/blob/v4/storage/schemadb/src/lib.rs#L102

**Comment by dboreham** [comment]
https://www.bookstack.cn/read/rocksdb-en/2f89b6c17fd1b7d4.md

https://www.bookstack.cn/read/rocksdb-en/b6f07d53a072be7d.md

https://github.com/facebook/rocksdb/wiki/Thread-Pool

**Comment by dboreham** [comment]
https://stackoverflow.com/questions/45572264/how-to-disable-rocksdb-database-debug-logging

**Comment by dboreham** [comment]
Good news: RocksDB debug logging (or, at least -- some logging) is enabled and written to `libradb/LOG`

In a devnet node, there are log messages that indicate compaction is at least being attempted. I need to learn to interpret the log output..

**Comment by dboreham** [comment]
> Mine hover around 65k, which I think is an upperbound somewhere

It's likely that it just has an fd to every single sbt file, and that our chain ends up producing 65k files today. Tomorrow : more.

**Comment by dboreham** [comment]
Some analysis of the `LOG` file on a db that exhibited the problem shows that compaction was occurring. RocksDB just likes to create a large number of leaf files (L4 in this case), of fairly small size (100K - 65M). This explains the large number of files. Probably there are tuning properties that can fix this, but this isn't the primary problem.

(note this conclusion is unconfirmed, based on static analysis of the code and various internet posts/articles)
The primary problem is that this tuning option: https://github.com/facebook/rocksdb/blob/master/include/rocksdb/options.h#L459 has the default value: -1
-1 means "never close any file descriptors". Only my opinion, but this is insane. This tuning parameter should never, ever be set to -1, and yet that's the default. Go. Figure.

We know it's set to -1 because `LOG` tells us:

```
$ grep Options.max_open_files LOG
2021/04/01-15:03:35.479920 7f977d4c3600                          Options.max_open_files: -1
```

Proposed fix: set `max_open_files` to something less than infinity, and definitely less than ulimit on the target system.

I'm not sure the implication of a very small value for max_open_files -- if rocksdb is sanely designed, you'd expect to only require as many fd's open as is required to serve the concurrent live database access pattern -- perhaps something like 100 would be plenty. A larger number avoids the overhead of closing and re-opening files, assuming rocksdb needs to access the same files over and over (probably an invalid assumption for our workload). Anyway, I'd suggest trying 1000.

More info here : https://www.bookstack.cn/read/rocksdb-6.14-en/313111 ("When options.max_open_files is set to -1, during DB open, all the SST files will be opened")

**Comment by lpgeiger** [comment]
@dboreham That's a great analysis. Let's try that! Want to send a PR to where that code change is?

**Comment by dboreham** [comment]
Something to consider is that there may be another problem driving this -- somehow we may be causing rocksdb to create small sst files. If the normal behavior is for sst files to be much larger (say, 2GB which is the typical large file size to avoid issues in some older FS with files > 2GB), then their default of "open all files forever" would, while not a good idea, not actually cause practical problems since you'd only be looking at a few 100 files max.

**Comment by arnojacobsen** [comment]
Doesn't really help us but we wanted to add it anyways.

Open FDs in a swarm of 1 node, running for about one hour, FDs seem to peter around in the 95s, about 2.5K blocks mined. Mode is test, i.e., mining delay is between 0-1 seconds. Not sure whether we can assume that the data production amount is similar to a libra-node / miner that's been running for 2.5K blocks.

2021-05-04:01-26-21   93
2021-05-04:01-26-36   93
2021-05-04:01-26-51   94
2021-05-04:01-27-06   94
2021-05-04:01-27-21   93
2021-05-04:01-27-36   93
2021-05-04:01-27-51   93
...
2021-05-04:02-20-45   95
2021-05-04:02-21-00   95
2021-05-04:02-21-15   95
2021-05-04:02-21-30   94
2021-05-04:02-21-45   95
2021-05-04:02-22-00   95

ls -lh *.sst
-rw-r--r-- 1 ubuntu ubuntu 27M May  3 23:16 000030.sst
-rw-r--r-- 1 ubuntu ubuntu 20M May  4 00:26 000032.sst
-rw-r--r-- 1 ubuntu ubuntu 17M May  4 01:22 000034.sst
-rw-r--r-- 1 ubuntu ubuntu 16M May  4 02:10 000036.sst

**Comment by dboreham** [comment]
https://github.com/tikv/rust-rocksdb/blob/master/src/rocksdb_options.rs#L757

**Comment by dboreham** [comment]
How to set an option : https://github.com/tikv/rust-rocksdb#apply-some-tunings

**Comment by dboreham** [comment]
Fix seems to be to set the `max_open_files` option here: https://github.com/OLSF/libra/blob/main/storage/schemadb/src/lib.rs#L218

**Comment by dboreham** [comment]
https://github.com/OLSF/libra/pull/533

**Comment by lpgeiger** [comment]
Thanks @dboreham looks good

**Comment by 0o-de-lally** [comment]
Seems resolved in v5 on testnet
