### ISSUE TITLE
[Bug] txs create-validator doesnt work

### ISSUE THREAD

**Issue by nelaturuk** [OLSF/libra#438]
![image](https://user-images.githubusercontent.com/3939682/114187204-baaa0680-9915-11eb-9c42-e0f250c568f7.png)

Create-validator seems to throw an abort error when executed. The command in documentation [here ](https://github.com/OLSF/libra/wiki/Validator-Onboarding-Guide)doesn't work.

**Comment by lpgeiger** [comment]
This is if you are using 4.2.8 txs tools on the chain which hasn't been upgraded to that version yet.
