### ISSUE TITLE
Are instructions to build as root correct?

### ISSUE THREAD

**Issue by dboreham** [OLSF/libra#450]
Here: https://github.com/OLSF/libra/wiki/Validator-Onboarding-Guide

it says:

![image](https://user-images.githubusercontent.com/1649760/115170952-20696180-a07f-11eb-89fe-f5abb2ace2f2.png)

Is that correct? (fwiw it doesn't work for me).

**Comment by lpgeiger** [comment]
Can I haz trace please :)

**Comment by dboreham** [comment]
```
$ sudo make bins
[sudo] password for ubuntu:
#Build and install genesis tool, libra-node, and miner
cargo run -p stdlib --release
bash: cargo: command not found
Makefile:43: recipe for target 'bins' failed
make: *** [bins] Error 127
```

**Comment by dboreham** [comment]
(in general building as root is a bad idea and it seems to work to build not as root).

**Comment by lpgeiger** [comment]
So that error for cargo is that you didn't complete the installation.  Seems you didn't initialize the cargo path, or reset the terminal. We probably need more instructions around that.

Also you are right sudo would only be needed for `make deps`.

**Comment by dboreham** [comment]
Cargo is on my user's path.
