### ISSUE TITLE
Onboarding flow for an existing validator key

### ISSUE THREAD

**Issue by dboreham** [OLSF/libra#451]
Trying to follow the process detailed in : https://github.com/OLSF/libra/wiki/Validator-Onboarding-Guide

with the following initial conditions:

 * Clean machine (no `~/.0L`)
 * Validator key previously generated (mnemonic retained somewhere).
 * Account creation transaction previously posted.

What happens:

When `ol onboard --next -t` is run, this happens:

```
$ ol onboard --next -t
Running manual onboarding, trigger_actions: true
Onboarding stage: EmptyBox
Triggering expected action
Running validator wizard
0L Account Address:
...........................
A924D8096294B5775E0CD82277F352FA

0L mnemonic:
...........................
xxx xxx xxx xxx xxx xxx xxx

WRITE THIS DOWN NOW. This is the last time you will see this mnemonic. It is not saved anywhere. Nobody can help you if you lose it.



Keys generated
...........................


Validator Config Wizard. Next you'll enter your mnemonic and some other info to configure your validator node and on-chain account. If you haven't yet generated keys you can re-run this command with the flag '--keygen', or run the standalone keygen subcommand with 'miner keygen'.

Your first 0L proof-of-work will be mined now. Expect this to take up to 15 minutes on modern CPUs.

Enter your 0L mnemonic:
```

**Comment by dboreham** [comment]
First question: what's with the two keys? Is it an error that a second mnemonic was generated above? Or do validators require two keys?

**Comment by lpgeiger** [comment]
Those instructions assume that this is the first time the user attempts to create account. Anyhow, the code is changes for release 4.3.0, and mnemonics are not generated on val-wizard.
