### ISSUE TITLE
[Tooling] Web monitor validators pane table view

### ISSUE THREAD

**Issue by lpgeiger** [OLSF/libra#504]
Data needed:
Address, voting power, epoch block proposals, epoch blocks signed, proofs mined

**Comment by soaresa** [comment]
Hi @lpgeiger , assign this issue to me please.

**Comment by soaresa** [comment]
To show validators epoch block proposals and epoch blocks signed at Web Monitor Validators Pane Table, I had to fetch ```ValsStats``` data from the chain and enrich ```Vitals.chain_view.validator_view```.

Both stats were added to the table as sortable columns:
![image](https://user-images.githubusercontent.com/10797037/120250444-8dfad700-c254-11eb-9c40-7fecebcfe3b0.png)

Note:
```rust
props = "block proposals"
votes = "blocks signed"
```

**Comment by soaresa** [comment]
Closed by #545
