### ISSUE TITLE
Web Monitor - concurrent cache reading and writing problem

### ISSUE THREAD

**Issue by soaresa** [OLSF/libra#511]
# 🐛 Bug

The web monitor server crashes on node environment because of the concurrent cache reading and writing problem.
While ```check::runner``` updates the ```monitor_cache.json``` file every second in one thread, another thread reads the same file every 10 seconds.
Eventually the reader will find the json incomplete crashing the app. On the dev environment it only prints error messages.

## To reproduce

**Code snippet to reproduce**
# Dev Env:
Start web monitor server after swarm is running with ```0L.toml``` initialized for both nodes (bob and alice).
```rust
cargo r -- --swarm-path <path-to-swarm> serve
```
# Node env:
```rust
ol serve -c
```

**Stack trace/error message**
```
The application panicked (crashed).
Message:  file should be proper JSON: Error("EOF while parsing a string", line: 1, column: 833)
Location: ol/cli/src/cache.rs:44
```
Dev env:
![image](https://user-images.githubusercontent.com/10797037/119423727-5501b600-bcda-11eb-9496-22f8812ac985.png)

Node env:
![image](https://user-images.githubusercontent.com/10797037/119478190-fcf0a100-bd25-11eb-85ce-c6143455788c.png)

## Expected Behavior
Web monitor server should not crash and no error message should be thrown by the server regarding writing and reading cache.

## System information

**Please complete the following information:**
- Libra Version: v4.3.1
- Rust Version: v1.46.0
- Computer OS: "Ubuntu v20.04.2 LTS (Focal Fossa)" 

## Additional context
Reducing intervals duration to read and write cache will reproduce the problem in seconds.

## Solution
Use a temp cache file to write the content and than rename it replacing the old cache file.

**Comment by soaresa** [comment]
I will submit a pull request with the solution for this issue but I don't have permission to assign it to me.

**Comment by lpgeiger** [comment]
@soaresa Can you send a hot fix?
