### ISSUE TITLE
Doc [Minor]

### ISSUE THREAD

**Issue by simsekgokhan** [OLSF/libra#529]
@lpgeiger 
Do we want to say "un-parallelized" ? `--test-threads 1` will run all tests on main thread, disables multi threaded testing.

```
..
# Tests can be parallelized. If you suspect side-effects. Run with 
> cargo test <keyword> -- --test-threads 1
..
```
https://github.com/OLSF/libra/wiki/Testing-0L

------

And broken links:  

1

```
Faster Sync: sync the state from a later waypoint [Link]
```
https://github.com/OLSF/libra/wiki/Syncing-the-State-to-Latest-State

2

```
https://github.com/OLSF/epoch-archive/tree/main/state_ver_41315058.6168
```
https://github.com/OLSF/libra/wiki/Syncing-from-an-advanced-Waypoint

**Comment by lpgeiger** [comment]
Patched.

#1 is now https://github.com/OLSF/libra/wiki/Restore-DB:-Syncing-from-an-advanced-Waypoint

#2 is deprecated
