### ISSUE TITLE
[Upgrade] Keep upgrade state out of 0x0, and in 0x2

### ISSUE THREAD

**Issue by 0o-de-lally** [OLSF/libra#537]
Hypothesis:
Moving the upgrade state out of 0x0 will make the block prologue faster by reducing the size of 0x0 state.

Research:
- [ ] Test if Upgrade state can live in a different path, e.g. 0x2
- [ ] Test if Upgrade state can be migrated from 0x0 to 0x2 without halting.

**Comment by jamesmeijers** [comment]
@lpgeiger We no longer need to worry about the halting issue, right? If we get this into the v5 upgrade?

**Comment by lpgeiger** [comment]
Yes, if we can move Upgrade state to 0x2 now, then we don't need to worry about migration.
