### ISSUE TITLE
[Web] Update web files from cli

### ISSUE THREAD

**Issue by 0o-de-lally** [OLSF/libra#542]
Web files should be downloaded by cli with command `ol serve --update`. 

Currently users are using libra/Makefile recipe web-files as a workaround.

There's a scaffold in ol/cli/src/commands/serve_cmd.rs

**Comment by soaresa** [comment]
What about building the web files locally and than moving to the 0L folder?

**Comment by lpgeiger** [comment]
Some (many?) users will not have the source, and instead be running from binaries.

**Comment by soaresa** [comment]
Got it! The onboarding easy mode does not need the project checkout and only install the binaries.
