### ISSUE TITLE
[Web Monitor + Audit] Show validators configs and audit them

### ISSUE THREAD

**Issue by soaresa** [OLSF/libra#570]
# 🚀 Feature Request

A) Show autopay instructions and more configs of validators in the validator set.
B) Create an audit smart contract to drop off validators misconfigured.

## Motivation

A) To bring more transparency of validators for better decision making.
B) To remove validators not following the necessary configs defined by social consensus.

## Additional context

A) Web-monitor changes:

1) Dash: 
- add 2 operator checks
- show operator balance
![image](https://user-images.githubusercontent.com/10797037/126022614-c4f22b79-84cb-427f-8964-126902f60016.png)

2) Audit:
Creates audit page to check summary and details of validators configs:
![image](https://user-images.githubusercontent.com/10797037/126022656-2b1e292a-6e70-421e-898e-cb11cac0c4ab.png)

3) Watch List:
Creates the Watch List page to show all percent of change autopay instructions in a sortable table including an account dictionary json file to add notes to account address:
![image](https://user-images.githubusercontent.com/10797037/126022709-fe85f13b-0b6a-4302-93a4-7952ade0e7f2.png)

4) Autopay:
Adds summary to Autopay page and account notes to the page table:
![image](https://user-images.githubusercontent.com/10797037/126022750-dad2262a-5b0a-4613-8c94-702d5fa7e7e3.png)

B) Audit Smart Contract
Validator will be drop off from the validator set if one of the following conditions return false:
```
      // has valid configs
      if (!ValidatorConfig::is_valid(val)) return false;

      // has operator account set to another address
      let oper = ValidatorConfig::get_operator(val);
      if (oper == val) return false;

      // operator account has balance
      if (LibraAccount::balance<GAS>(oper) < 50000) return false;

      // has autopay enabled
      if (!AutoPay2::is_enabled(val)) return false;

      // has mining state
      if (!MinerState::is_init(val)) return false;
```

**Comment by lpgeiger** [comment]
@soaresa  I think we can simplify this view. We can drop the previous balance column, which is just an internal tracking field. We can also set the instruction type to use the same semantics as in ol/types/autopay.rs, so that it is more descriptive. i.e. 1 == "Percent of Inflow" etc.

<img width="1436" alt="Screen Shot 2021-06-21 at 2 19 57 PM" src="https://user-images.githubusercontent.com/1364012/122809264-e04f7680-d29b-11eb-87d8-b0612614813d.png">

**Comment by soaresa** [comment]
@lpgeiger , PR #579 adds these suggestions.

**Comment by soaresa** [comment]
![image](https://user-images.githubusercontent.com/10797037/127385501-f6ec4b4a-e4bc-430c-b8c2-6be2d96293ae.png)
