### ISSUE TITLE
[Bug] CLI: `ol start` pilot functionality panics when cannot reach an upstream URL

### ISSUE THREAD

**Issue by lpgeiger** [OLSF/libra#621]
If the node only has one upstream for json rpc, and that upstream is offline, the `ol start` command will panic. 

Remedies:
1. This needs to be handled gracefully.
2. The query should fallback onto the next upstream in the list of upstreams.
3.  The user should optionally be able to refresh the list of upstreams from on-chain info, e.g. fullnode networks.

 
Error message:
```
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: error sending request for url (http://68.183.61.250:8080/): error trying to connect: tcp connect error: Connection refused (os error 111)

Caused by:
    0: error trying to connect: tcp connect error: Connection refused (os error 111)
    1: tcp connect error: Connection refused (os error 111)
    2: Connection refused (os error 111)
Location: ol/cli/src/node/sync.rs:49
```

**Comment by liangping** [comment]
https://github.com/OLSF/libra/commit/6c302179fb67ca751205ca8ec0ae9808b894a11d

Hello @lpgeiger @soaresa . I made a change in client. Could you make a test. It's pretty slow to connect this server from my computer.
