### ISSUE TITLE
[Bug] ol serve -c, is panicking due to tokio thread

### ISSUE THREAD

**Issue by 0o-de-lally** [OLSF/libra#693]
Reproduce with: 
cargo r -p ol -- serve -c

Yields:

     Running `target/debug/ol serve -c`
Sep 17 17:08:34.629  INFO ureq::unit: sending request POST http://localhost:8080/
Sep 17 17:08:34.639  INFO ureq::unit: sending request POST http://localhost:8080/
The application panicked (crashed).
Message:  there is no reactor running, must be called from the context of a Tokio 1.x runtime

<img width="848" alt="Screen Shot 2021-09-17 at 1 08 25 PM" src="https://user-images.githubusercontent.com/1364012/133827456-0d874a9b-4e7f-47e2-b7a2-326a355cdc9d.png">

**Comment by simsekgokhan** [comment]
I have seen this error before. This is due to tokio version incompatibility. Breaking changes with tokio 1.0.

**Comment by 0o-de-lally** [comment]
@simsekgokhan  I still see a similar error with `cargo r -p ol -- serve`. I wonder if the serve subcommand has dependencies using a different version. Also, abscissa has a very specific way tokio should be called, which we had worked around previously.

**Comment by simsekgokhan** [comment]
Interesting, yes I also got similar error now:

```
Running `target/debug/ol -s /opt/swarm_temp/ serve -c`
[sdk/client/src/blocking.rs:159] "get_miner_state" = "get_miner_state"
The application panicked (crashed).
Message:  there is no reactor running, must be called from the context of a Tokio 0.2.x runtime
Location: /home/gsimsek/.cargo/registry/src/github.com-1ecc6299db9ec82
```

Yes, as you guessed abscissa-tokio 0.5 uses tokio 0.2.: 
https://github.com/OLSF/libra/blob/634ebd2da4d248ae09d70632a88682d1779aebec/ol/cli/Cargo.toml#L54

https://github.com/iqlusioninc/abscissa/blob/tokio/v0.5.1/tokio/Cargo.toml#L17


BTW, abscissa-tokio uses tokio 1.x in latest version: 
https://github.com/iqlusioninc/abscissa/blob/tokio/v0.6.0-pre.2/tokio/Cargo.toml#L14

**Comment by simsekgokhan** [comment]
Hmm, I reverted my changes (tokio upgrade) and it did not crash. I have this output:

```
target/debug/ol -s /opt/swarm_temp/ serve -c`
[sdk/client/src/blocking.rs:159] "get_miner_state" = "get_miner_state"
Sep 29 16:01:07.914  INFO warp::server: listening on http://0.0.0.0:3030
[sdk/client/src/blocking.rs:159] "get_miner_state" = "get_miner_state"
[sdk/client/src/blocking.rs:159] "get_miner_state" = "get_miner_state"
[sdk/client/src/blocking.rs:159] "get_miner_state" = "get_miner_state"
[sdk/client/src/blocking.rs:159] "get_miner_state" = "get_miner_state"
```

This branch if you want to verify: 
https://github.com/OLSF/libra/pull/723

**Comment by 0o-de-lally** [comment]
@simsekgokhan I tried this on a production node and I still get the error. Except this time with a `1.x` in the message. @soaresa is looking at migrating to an up to date version.

**Comment by soaresa** [comment]
I was able to fix this issue and I will submit a PR soon.

**Comment by simsekgokhan** [comment]
> @simsekgokhan I tried this on a production node and I still get the error. Except this time with a `1.x` in the message. @soaresa is looking at migrating to an up to date version.

Ok. I used main branch and ol/cli with tokio 0.2 yesterday, no crash. (as seen from the logs I shared)
