### ISSUE TITLE
[Bug] Submitting VDF proofs as non-validator user is not possible

### ISSUE THREAD

**Issue by mortonbits** [OLSF/libra#807]
# 🐛 Bug

Submitting VDF proofs as non-validator user is not possible.

Also the documentation should be updated to describe better how to mine & submit VDF proofs on chain as normal user:
https://github.com/OLSF/libra/blob/main/ol/documentation/node-ops/tower_mining_VDF_proofs.md

## To reproduce

**Command snippet to reproduce**

As non-validator user :
```
tower start
```

**Stack trace/error message**
```
Error fetching remote state: Error { inner: Inner { kind: JsonRpcError, source: None, json_rpc_error: Some(JsonRpcError { code: -32000, message: "Server error: could not get tower state", data: None }) } }
ERROR: Failed fetching remote state, message: Error fetching remote state: Error { inner: Inner { kind: JsonRpcError, source: None, json_rpc_error: Some(JsonRpcError { code: -32000, message: "Server error: could not get tower state", data: None }) } }
```

## Expected Behavior

- Initial tower height should be returned as 0
- it should be possible to submit VDF proofs to the chain

## System information

libra tag v5.0.2

**Comment by sm86** [comment]
Are you running a full node on this? If not, you should probably connect to one using URL
