### ISSUE TITLE
怎么安装OL挖矿软件，怎么才是开始挖矿有视频吗

### ISSUE THREAD

**Issue by wan520hong** [OLSF/libra#863]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discourse](https://community.libra.org)

**Comment by 0o-de-lally** [comment]
@liangping  can you close this with https://github.com/OLSF/libra/commit/58591b93dfc5a9ac67fda09e848de5aeb5186f47

**Comment by liangping** [comment]
暂时没有视频，有文字版，请参考上一个回复
