### ISSUE TITLE
怎么才可以挖OL，有教程吗

### ISSUE THREAD

**Issue by wan520hong** [OLSF/libra#864]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discourse](https://community.libra.org)

**Comment by wan520hong** [comment]
看不懂，可以用其它方式对话吗，想请教你一下

**Comment by wan520hong** [comment]
下载好了，就不知道怎么搞才可以挖矿

**Comment by 0o-de-lally** [comment]
@liangping  can you close this with https://github.com/OLSF/libra/commit/58591b93dfc5a9ac67fda09e848de5aeb5186f47

**Comment by liangping** [comment]
Done
