### ISSUE TITLE
[Feature Request][txs] Create validator-config subcommand to txs app so validators can update on-chain discovery info

### ISSUE THREAD

**Issue by 0o-de-lally** [OLSF/libra#904]
Validators need a tool to be able to update their on-chain configuration such as networking.

The Move tx scripts is ValidatorAdministrationScripts::register_validator_config

https://github.com/OLSF/libra/blob/1292f55fe8ddd6ab5255094364cc10dd9d194b8e/language/diem-framework/modules/ValidatorAdministrationScripts.move#L140-L155

The ol txs sending tool is the CLI tool to send transactions to network.

An unrelated subcommand, which serves as an example is the authentication key rotation subcommand. Seen here:

https://github.com/OLSF/libra/blob/3b2e34cb794ca3f4a7da8e0b1a4e3b211e8d7759/ol/txs/src/commands/authkey_cmd.rs#L22-L41

**Comment by mortonbits** [comment]
Hi @Leibniz137 - I continued on this topic and made a commit in my repository: 
https://github.com/mortonbits/libra/pull/new/feature/mb-change-vlad-ip

Can you have a look on this? I changed it to ask interactively for the new IP by re-using the dialogue from the "ol init" command.

@0o-de-lally - the method register_validator_config expects 2 addresses, one for the validator and one for the full node. Is it ok to take the same IP for both? Or should we let the user specify the VFN address for the fullnode_network_address?

**Comment by 0o-de-lally** [comment]
@mortonbits  and @leibniz137 I have a PR that does this, its a little more involved than taking an IP address. See here: https://github.com/OLSF/libra/pull/938
